"""Membuat tabel awal untuk MySQL

Revision ID: 58bae2a43a7b
Revises: 
Create Date: 2025-06-25 19:21:33.809541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bae2a43a7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kecamatan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kecamatan', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_kecamatan')
    )
    op.create_table('laporan_masyarakat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pelapor', sa.String(length=100), nullable=False),
    sa.Column('kontak_pelapor', sa.String(length=50), nullable=True),
    sa.Column('nama_korban_dilaporkan', sa.String(length=150), nullable=True),
    sa.Column('lokasi_penemuan', sa.Text(), nullable=True),
    sa.Column('kondisi_saat_ditemukan', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('status_verifikasi', sa.String(length=50), nullable=False),
    sa.Column('tanggal_laporan', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laporan_masyarakat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laporan_masyarakat_status_verifikasi'), ['status_verifikasi'], unique=False)

    op.create_table('petugas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('info_bencana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('konten', sa.Text(), nullable=False),
    sa.Column('terakhir_diperbarui', sa.DateTime(), nullable=True),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['petugas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kecamatan_id')
    )
    op.create_table('korban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=150), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=True),
    sa.Column('usia', sa.Integer(), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=True),
    sa.Column('alamat_asal', sa.Text(), nullable=True),
    sa.Column('lokasi_ditemukan', sa.String(length=255), nullable=True),
    sa.Column('status_korban', sa.String(length=50), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('tanggal_update', sa.DateTime(), nullable=True),
    sa.Column('kecamatan_id', sa.Integer(), nullable=False),
    sa.Column('petugas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ),
    sa.ForeignKeyConstraint(['petugas_id'], ['petugas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('korban', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_korban_nama_lengkap'), ['nama_lengkap'], unique=False)
        batch_op.create_index(batch_op.f('ix_korban_nik'), ['nik'], unique=True)
        batch_op.create_index(batch_op.f('ix_korban_status_korban'), ['status_korban'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('korban', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_korban_status_korban'))
        batch_op.drop_index(batch_op.f('ix_korban_nik'))
        batch_op.drop_index(batch_op.f('ix_korban_nama_lengkap'))

    op.drop_table('korban')
    op.drop_table('info_bencana')
    op.drop_table('petugas')
    with op.batch_alter_table('laporan_masyarakat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laporan_masyarakat_status_verifikasi'))

    op.drop_table('laporan_masyarakat')
    op.drop_table('kecamatan')
    # ### end Alembic commands ###
